### ISSUE TITLE
The validation logics related

### ISSUE THREAD

**Issue by geonsangyoo** [phann-phearoen/mamasuku-repos#10]
@phann-phearoen 

In terms of validation logics for each input forms,

1.
<img width="873" alt="Screen Shot 2021-07-22 at 1 05 57" src="https://user-images.githubusercontent.com/14138179/126522360-0650477a-5241-4f29-9ead-e3591caff740.png">

2.
<img width="707" alt="Screen Shot 2021-07-22 at 1 10 07" src="https://user-images.githubusercontent.com/14138179/126522528-0d2c6030-ed37-40fa-88cb-7fd815159d5e.png">

3.
<img width="852" alt="Screen Shot 2021-07-22 at 1 11 28" src="https://user-images.githubusercontent.com/14138179/126522914-7af51111-7524-477a-bf08-7ee2c8c5af49.png">

- [x] please translate warning messages into Japanese. please investigate `QUASAR` framework on the validation logic support if you cannot make sure how to deal with it. [https://quasar.dev/vue-components/input#validation](https://quasar.dev/vue-components/input#validation)

- [x] please add validation logics for phone number input form(電話番号) and date format(ご希望の日時) on reservation form.

**Comment by phann-phearoen** [comment]
![image](https://user-images.githubusercontent.com/74291680/126966119-dfa4e412-3c78-4356-8440-4d0e4d558711.png)
![image](https://user-images.githubusercontent.com/74291680/126966328-73fd5ceb-e0ef-4102-bda5-120312183493.png)

The form looks and validation logic seems and feels nice already, and all the issues are already primarily fixed too.

However, I have a hard time figuring out how to manage the data structure of the ご希望の日時. 

As you can see we have 3 separated sets of 3 input fields. In order to bind those fields we need 9 data properties. Consider using Vuex, we need set & get function combine with the validation functions, there seem to be too many functions, which is not a programming should be.

Please help me in this issue, it's really out of my hands.

**Comment by geonsangyoo** [comment]
@phann-phearoen 

it can be confirmed. I get it closed.
